appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jw5BaM8eEbY5q5q75Zkc9jehKOg8/97Q4VSGryIw0m2ZaAwtSi8kXJg4iP01S7Mu8y4Lh9USrX57bHvvCvswoBNy8Ma3yyP0ypt2G6lx14ylf9bUFaKUi0AEDaXwuL6mkkLJjp/HvQJirGEhmCkKnAPQgLiNUHK+pWW9t/eJDq6+o3BkySCkNMbK7Vkzjsdr7W5zXEYQ47nFLkfOM1F7u7FeDHBKvS97gRwrCnGsIAu8kgz6VfeCv1fv65k30L6JayKdyiY4M3qsclHq0FMplCLyGq+JzSohuusOqfToT8m3Qc/XryxLPDSlf8zix12npGXCg9HVGXxpkzY0jQ96TIPaJCEWmXENNUomsoC+rvjJD4pgo7qOhlwKcD2o30oF7aB4RFfBPBzzd06tnXOBw4fi9W3/tmnHNsdoJniDssgUVESU60AqBHKj6fQ6ak72M+8kU5J7aMdr/k6yGJ6gEBRr/9P7tP26AZxh2tr5i/x8PsSAf4uxxieQyaZwfXQAYcRYn5afabLmbh+6Ov34DEk1agAzpQqiTH2W1utArVlksOWy0tlharyvMqseSARbdV0rawUcDUerJhTQXwnNH+LTmd+CFfPVZLUfzaNJcuKCFWUXyxxD1Y1MCUniIKjn+zCH6KTSSO/3g6R5TaKP5x4CLYFWxliSGtkFM3bFRGw=}
